insert into filejolt.usuario values (1, 'mkearl@gmail.com', 'Juliana Correia', 'zwngpathbrx');
insert into filejolt.usuario values (2, 'treeves@yahoo.com', 'Benício da Paz', 'ajiqawbu');
insert into filejolt.usuario values (3, 'daveed@yahoo.com', 'Pietro Silveira', 'ch0fynt5');
insert into filejolt.usuario values (4, 'treekoo@yahoo.com', 'Thiago da Rocha', 'k9c0s2q7');
insert into filejolt.usuario values (5, 'aracne@outlook.com', 'Pedro Lucas Oliveira', 'r2jl8z49');
insert into filejolt.usuario values (6, 'hoangle@gmail.com', 'Davi Porto', 'jo9twnb5');
insert into filejolt.usuario values (7, 'gospodin@msn.com', 'Maria Alice da Rosa', 'zck54i9t');
insert into filejolt.usuario values (8, 'penna@outlook.com', 'Daniel Araújo', 'tvxe4zn1');
insert into filejolt.usuario values (9, 'report@live.com', 'Sophia Gomes', 'fw287g3m');
insert into filejolt.usuario values (10, 'weidai@gmail.com', 'Marina Martins', 'v3b2d413');
insert into filejolt.usuario values (11, 'pgolle@outlook.com', 'Caio Carvalho', 'nf8zkl7n');
insert into filejolt.usuario values (12, 'baveja@live.com', 'Maria Clara Freitas', 'sxmpkd4f');
insert into filejolt.usuario values (13, 'bescoto@live.com', 'Cauã Fogaça', 'cnj7loji');
insert into filejolt.usuario values (14, 'blixem@outlook.com', 'Gustavo Moreira', 'hlb7qzh2');
insert into filejolt.usuario values (15, 'trieuvan@yahoo.com', 'Lucca Moreira', 'olto211n');
insert into filejolt.usuario values (16, 'isaacson@gmail.com', 'Theo Moreira', 'jhyqmcbd');
insert into filejolt.usuario values (17, 'saridder@gmail.com', 'Elisa Porto', 'w2q6sr65');
insert into filejolt.usuario values (18, 'dalamb@hotmail.com', 'Cecília Sales', 'jnryhj8y');
insert into filejolt.usuario values (19, 'fmtbebuck@hotmail.com', 'Ana Júlia Lopes', 'b2pfvo6r');
insert into filejolt.usuario values (20, 'forsberg@msn.com', 'Leandro Jesus', 'z79vi871');
insert into filejolt.usuario values (21, 'mailarc@msn.com', 'Davi da Conceição', 'hde9pmsd');

insert into filejolt.arquivo values (1, 'mainlining', 'Mainlining is a new take on the traditional point and click adventure. The entire game takes place on the simulated desktop of the protagonists computer. Assuming the role of an MI7 agent, the player must use their skill and cunning to gather evidence by hacking suspects computers and phones.', 'Mainlining', 165);
insert into filejolt.arquivo values (3, 'dont_talk_tostrangers', 'You just arrived in a new city with your family after your parents changed jobs. And its Halloween. Your mother warned to not talk to strangers your whole life. But its Halloween. You gotta get that sweet sweet glorious candy. So you go. If you get to know them, maybe they are not strangers anymore? So it would be ok to go trick or treating then. But be careful. If something looks strange, you can always leave. Good luck.', 'Dont Talk to Strangers', 516);
insert into filejolt.arquivo values (4, 'my_time_at_portia', 'My Time at Portia is a simulation open world RPG game. The world is set in a post-apocalypse setting. Humans are few and relics from the past are everywhere. The player will need to start a new life in a town on the edge of civilization called Portia. The player will start a workshop and build things with relics from the past for the betterment of society. The goal of the game is to make the workshop as big as possible.', 'My Time At Portia', 3265);
insert into filejolt.arquivo values (7, 'glitch_in_the_system', 'When Jack sits down to record for the day, his computer doesnt seem to want to cooperate. In fact, it seems to be fighting against him, and he suddenly finds himself pulled back into the weird and wonderful world of Wireland! But theres something wrong, this time. Something off. Something that seems to be pulling the fragile world of his favorite characters apart at the very seams. Its up to Jack, along with the rest of Possepticeye, to find out whats behind this...or who. ', 'Glitch in the System', 215);
insert into filejolt.arquivo values (8, 'heartbound', 'Heartbound is a non-traditional role-playing game about a boy, his dog, secrets, and sanity.', 'Heartbound', 1548);
insert into filejolt.arquivo values (12, 'dude_stop ', 'Dude, Stop is a puzzle game, where the main goal is to make everyone hate you. And I mean it! If someone would watch you play, they could slap you upside the head and call you The Most Evil Person alive! And we are not even sorry about that! Because we know that deep down in your soul… ', 'Dude, Stop ', 6896);
insert into filejolt.arquivo values (15, 'spookys_jump_scare_mansion', 'Can you survive 1000 rooms of cute terror? Or will you break once the cuteness starts to fade off and your running for your life from the unspeakable hideous beings that shake and writhe in bowels of this house? They wait for you, they wait and hunger for meeting you. They long to finally meet you and show you how flexible your skin can be after it has soaked in blood.', 'Spookys Jump Scare Mansion', 4748);
insert into filejolt.arquivo values (20, 'long_gone_days', 'Long Gone Days is a 2D modern-day military RPG set in our current times, with a focus on language and cultural barriers, inspired by classic dystopian literature and visual novels.', 'Long Gone Days', 2135);
insert into filejolt.arquivo values (7, 'the_fall_of_lazarus', 'The Fall of Lazarus is a first person exploration game set in a science fiction future. You are a crew member of the USSC Lazarus waking up from cryo sleep without memories and even without name in an apparently abandoned drifting cargo spaceship. But you’re not alone, there is also Hybris, the Artificial intelligence who commands the ship.', 'The Fall of Lazarus', 256);
insert into filejolt.arquivo values (8, 'the_wild_eight', 'The game tells the story of eight people whose everyday lives are forever changed after a horrific plane crash. They now find themselves stranded in the middle of nowhere, deep in the forests of Alaska. Welcome to a world without civilization, where you and the other survivors are at the mercy of nature — and wild animals starved by the cold!', 'The Wild Eight', 5748);
insert into filejolt.arquivo values (3, 'polywar', 'a fast paced multiplayer fps game that focuses on creative weapons and game mechanics that reward skillfull killing.', 'Polywar', 987);
insert into filejolt.arquivo values (15, 'rainfall', 'RAIN|FALL is an original, indie 2D adventure game in which every decision you make, in-game or in dialogue has consequences and change the story. Instead of pointing-and-clicking, you walk around the scenes with arrows or WASD.', 'RAINFALL', 54);
insert into filejolt.arquivo values (21, 'light_fairytale', 'Light Fairytale is a turn-based Japanese-style RPG series set in a dying underground world ruled by an evil empire.', 'Light Fairytale', 678);
insert into filejolt.arquivo values (20, 'minotaur', 'Minotaur’s story is mainly focused on nine characters who come to find themselves trapped in their apartment building. Nod’s route, which is fully available in this Early Access release, follows a synthet named Nod Pikes as he attempts to escape and come to terms with his past – with help (kind of) from his lovely sharp-tongued AI assistant Ollie. ', 'Minotaur', 954);
insert into filejolt.arquivo values (8, 'a_dragon_named_coal', 'Civil war hollows out a legendary kingdom to a husk of its former glory. In a last effort to save his people a king embarks on one last quest. But a young outcasted dragon named Coal may be able to accomplish what the king’s great armies and sorcerers cannot. For his decisions will echo throughout generations to doom or save everyone.', 'A Dragon Named Coal', 123);

insert into filejolt.avalia values (1, 2, 'mainlining', 1, 5.2);
insert into filejolt.avalia values (3, 5, 'dont_talk_tostrangers', 1.3, 3);
insert into filejolt.avalia values (4, 6, 'my_time_at_portia', 2, 7);
insert into filejolt.avalia values (7, 9, 'glitch_in_the_system', 2.1, 6.4);
insert into filejolt.avalia values (8, 10, 'heartbound', 1, 4.1);
insert into filejolt.avalia values (12, 11, 'dude_stop ', 2.6, 2.5);
insert into filejolt.avalia values (15, 13, 'spookys_jump_scare_mansion', 1.5, 7.9);
insert into filejolt.avalia values (20, 14, 'long_gone_days', 1.1, 8);

insert into filejolt.comenta values (1, 16, 'mainlining', 1.0, 'Honestamente, o nome soa como um jogo de fãs de undertale. Mas quando eu joguei o jogo fiquei tão impressionado com os personagens clássicos');
insert into filejolt.comenta values (3, 17, 'dont_talk_tostrangers', 1.3, 'para ser honesto o primeiro eu estava prestes a cair em lágrimas no final. mas adorei como vocês adicionaram todos os personagens de alguns dos jogos que os jacks já jogaram. também amo a dublagem, a história, o diálogo, o ocs o trabalho de arte, a música como todo o caminho, tudo, até mesmo todos os Billys e todos os jacks. ');
insert into filejolt.comenta values (4, 18, 'my_time_at_portia', 2.0, 'Uau! Este jogo foi extremamente bem feito, na verdade eu pretendo jogar mais e estou bastante animado para ver o que mais vocês têm reservado para isso! Estilo de arte absolutamente adorável e uma grande variedade de personagens andando pelo mundo, que eu amei! ');
insert into filejolt.comenta values (7, 19, 'glitch_in_the_system', 2.1, 'é maravilhoso. no meio do jogo, eu tinha esquecido que era uma demo... eu pirei no gancho do penhasco.. xd .... de qualquer forma, mesmo sendo apenas uma demo, foi de longe a melhor coisa que eu já fiz reproduziu. estou ansioso para ver o projeto finalizado. boa sorte!');
insert into filejolt.comenta values (8, 21, 'heartbound', 1.0, 'Esse jogo é incrível, quero mais, quero saber o que vai acontecer com Rourke e Adair!');
insert into filejolt.comenta values (12, 3, 'dude_stop ', 2.6, 'Joguei seu jogo e me diverti muito, mas pergunte: Existe alguma maneira de simplesmente não fazer as tarefas, ou você está apenas brincando com a gente?');
insert into filejolt.comenta values (15, 4, 'spookys_jump_scare_mansion', 1.5, 'Eu amo muito esse jogo! É tão fofo (e assustador) haha. Fiz um vídeo de gameplay no YouTube. Aqui está o link se você quiser dar uma olhada! Obrigado :)');
insert into filejolt.comenta values (20, 8, 'long_gone_days', 1.1, 'Eu não posso acreditar que acabei de encontrar este jogo agora! Eu gostaria de ter encontrado antes! Mas de qualquer forma, eu pensei que esta demo era absolutamente incrível. No curto espaço de tempo que tivemos para jogar, eu já podia dizer que o jogo completo seria ótimo!');

